// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AuthsColumns holds the columns for the "auths" table.
	AuthsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "app_id", Type: field.TypeUUID},
		{Name: "third_party_id", Type: field.TypeUUID},
		{Name: "app_key", Type: field.TypeString},
		{Name: "app_secret", Type: field.TypeString},
		{Name: "redirect_url", Type: field.TypeString},
	}
	// AuthsTable holds the schema information for the "auths" table.
	AuthsTable = &schema.Table{
		Name:       "auths",
		Columns:    AuthsColumns,
		PrimaryKey: []*schema.Column{AuthsColumns[0]},
	}
	// ThirdPartiesColumns holds the columns for the "third_parties" table.
	ThirdPartiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "brand_name", Type: field.TypeString},
		{Name: "logo", Type: field.TypeString},
		{Name: "domain", Type: field.TypeString},
	}
	// ThirdPartiesTable holds the schema information for the "third_parties" table.
	ThirdPartiesTable = &schema.Table{
		Name:       "third_parties",
		Columns:    ThirdPartiesColumns,
		PrimaryKey: []*schema.Column{ThirdPartiesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AuthsTable,
		ThirdPartiesTable,
	}
)

func init() {
}
