// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/notification/pkg/db/ent/mailbox"
	"github.com/NpoolPlatform/notification/pkg/db/ent/predicate"
)

// MailBoxDelete is the builder for deleting a MailBox entity.
type MailBoxDelete struct {
	config
	hooks    []Hook
	mutation *MailBoxMutation
}

// Where appends a list predicates to the MailBoxDelete builder.
func (mbd *MailBoxDelete) Where(ps ...predicate.MailBox) *MailBoxDelete {
	mbd.mutation.Where(ps...)
	return mbd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mbd *MailBoxDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mbd.hooks) == 0 {
		affected, err = mbd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MailBoxMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mbd.mutation = mutation
			affected, err = mbd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mbd.hooks) - 1; i >= 0; i-- {
			if mbd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mbd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mbd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (mbd *MailBoxDelete) ExecX(ctx context.Context) int {
	n, err := mbd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mbd *MailBoxDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: mailbox.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: mailbox.FieldID,
			},
		},
	}
	if ps := mbd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, mbd.driver, _spec)
}

// MailBoxDeleteOne is the builder for deleting a single MailBox entity.
type MailBoxDeleteOne struct {
	mbd *MailBoxDelete
}

// Exec executes the deletion query.
func (mbdo *MailBoxDeleteOne) Exec(ctx context.Context) error {
	n, err := mbdo.mbd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mailbox.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mbdo *MailBoxDeleteOne) ExecX(ctx context.Context) {
	mbdo.mbd.ExecX(ctx)
}
