// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/third-login-gateway/pkg/db/ent/platform"
	"github.com/google/uuid"
)

// PlatformCreate is the builder for creating a Platform entity.
type PlatformCreate struct {
	config
	mutation *PlatformMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (pc *PlatformCreate) SetCreatedAt(u uint32) *PlatformCreate {
	pc.mutation.SetCreatedAt(u)
	return pc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pc *PlatformCreate) SetNillableCreatedAt(u *uint32) *PlatformCreate {
	if u != nil {
		pc.SetCreatedAt(*u)
	}
	return pc
}

// SetUpdatedAt sets the "updated_at" field.
func (pc *PlatformCreate) SetUpdatedAt(u uint32) *PlatformCreate {
	pc.mutation.SetUpdatedAt(u)
	return pc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pc *PlatformCreate) SetNillableUpdatedAt(u *uint32) *PlatformCreate {
	if u != nil {
		pc.SetUpdatedAt(*u)
	}
	return pc
}

// SetDeletedAt sets the "deleted_at" field.
func (pc *PlatformCreate) SetDeletedAt(u uint32) *PlatformCreate {
	pc.mutation.SetDeletedAt(u)
	return pc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (pc *PlatformCreate) SetNillableDeletedAt(u *uint32) *PlatformCreate {
	if u != nil {
		pc.SetDeletedAt(*u)
	}
	return pc
}

// SetAppID sets the "app_id" field.
func (pc *PlatformCreate) SetAppID(u uuid.UUID) *PlatformCreate {
	pc.mutation.SetAppID(u)
	return pc
}

// SetPlatform sets the "platform" field.
func (pc *PlatformCreate) SetPlatform(s string) *PlatformCreate {
	pc.mutation.SetPlatform(s)
	return pc
}

// SetPlatformAuthURL sets the "platform_auth_url" field.
func (pc *PlatformCreate) SetPlatformAuthURL(s string) *PlatformCreate {
	pc.mutation.SetPlatformAuthURL(s)
	return pc
}

// SetLogoURL sets the "logo_url" field.
func (pc *PlatformCreate) SetLogoURL(s string) *PlatformCreate {
	pc.mutation.SetLogoURL(s)
	return pc
}

// SetPlatformAppKey sets the "platform_app_key" field.
func (pc *PlatformCreate) SetPlatformAppKey(s string) *PlatformCreate {
	pc.mutation.SetPlatformAppKey(s)
	return pc
}

// SetPlatformAppSecret sets the "platform_app_secret" field.
func (pc *PlatformCreate) SetPlatformAppSecret(s string) *PlatformCreate {
	pc.mutation.SetPlatformAppSecret(s)
	return pc
}

// SetRedirectURL sets the "redirect_url" field.
func (pc *PlatformCreate) SetRedirectURL(s string) *PlatformCreate {
	pc.mutation.SetRedirectURL(s)
	return pc
}

// SetID sets the "id" field.
func (pc *PlatformCreate) SetID(u uuid.UUID) *PlatformCreate {
	pc.mutation.SetID(u)
	return pc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (pc *PlatformCreate) SetNillableID(u *uuid.UUID) *PlatformCreate {
	if u != nil {
		pc.SetID(*u)
	}
	return pc
}

// Mutation returns the PlatformMutation object of the builder.
func (pc *PlatformCreate) Mutation() *PlatformMutation {
	return pc.mutation
}

// Save creates the Platform in the database.
func (pc *PlatformCreate) Save(ctx context.Context) (*Platform, error) {
	var (
		err  error
		node *Platform
	)
	if err := pc.defaults(); err != nil {
		return nil, err
	}
	if len(pc.hooks) == 0 {
		if err = pc.check(); err != nil {
			return nil, err
		}
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PlatformMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pc.check(); err != nil {
				return nil, err
			}
			pc.mutation = mutation
			if node, err = pc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			if pc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PlatformCreate) SaveX(ctx context.Context) *Platform {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PlatformCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PlatformCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PlatformCreate) defaults() error {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		if platform.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized platform.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := platform.DefaultCreatedAt()
		pc.mutation.SetCreatedAt(v)
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		if platform.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized platform.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := platform.DefaultUpdatedAt()
		pc.mutation.SetUpdatedAt(v)
	}
	if _, ok := pc.mutation.DeletedAt(); !ok {
		if platform.DefaultDeletedAt == nil {
			return fmt.Errorf("ent: uninitialized platform.DefaultDeletedAt (forgotten import ent/runtime?)")
		}
		v := platform.DefaultDeletedAt()
		pc.mutation.SetDeletedAt(v)
	}
	if _, ok := pc.mutation.ID(); !ok {
		if platform.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized platform.DefaultID (forgotten import ent/runtime?)")
		}
		v := platform.DefaultID()
		pc.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (pc *PlatformCreate) check() error {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Platform.created_at"`)}
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Platform.updated_at"`)}
	}
	if _, ok := pc.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "Platform.deleted_at"`)}
	}
	if _, ok := pc.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "Platform.app_id"`)}
	}
	if _, ok := pc.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "Platform.platform"`)}
	}
	if _, ok := pc.mutation.PlatformAuthURL(); !ok {
		return &ValidationError{Name: "platform_auth_url", err: errors.New(`ent: missing required field "Platform.platform_auth_url"`)}
	}
	if _, ok := pc.mutation.LogoURL(); !ok {
		return &ValidationError{Name: "logo_url", err: errors.New(`ent: missing required field "Platform.logo_url"`)}
	}
	if _, ok := pc.mutation.PlatformAppKey(); !ok {
		return &ValidationError{Name: "platform_app_key", err: errors.New(`ent: missing required field "Platform.platform_app_key"`)}
	}
	if _, ok := pc.mutation.PlatformAppSecret(); !ok {
		return &ValidationError{Name: "platform_app_secret", err: errors.New(`ent: missing required field "Platform.platform_app_secret"`)}
	}
	if _, ok := pc.mutation.RedirectURL(); !ok {
		return &ValidationError{Name: "redirect_url", err: errors.New(`ent: missing required field "Platform.redirect_url"`)}
	}
	return nil
}

func (pc *PlatformCreate) sqlSave(ctx context.Context) (*Platform, error) {
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (pc *PlatformCreate) createSpec() (*Platform, *sqlgraph.CreateSpec) {
	var (
		_node = &Platform{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: platform.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: platform.FieldID,
			},
		}
	)
	_spec.OnConflict = pc.conflict
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := pc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: platform.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := pc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: platform.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := pc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: platform.FieldDeletedAt,
		})
		_node.DeletedAt = value
	}
	if value, ok := pc.mutation.AppID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: platform.FieldAppID,
		})
		_node.AppID = value
	}
	if value, ok := pc.mutation.Platform(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: platform.FieldPlatform,
		})
		_node.Platform = value
	}
	if value, ok := pc.mutation.PlatformAuthURL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: platform.FieldPlatformAuthURL,
		})
		_node.PlatformAuthURL = value
	}
	if value, ok := pc.mutation.LogoURL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: platform.FieldLogoURL,
		})
		_node.LogoURL = value
	}
	if value, ok := pc.mutation.PlatformAppKey(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: platform.FieldPlatformAppKey,
		})
		_node.PlatformAppKey = value
	}
	if value, ok := pc.mutation.PlatformAppSecret(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: platform.FieldPlatformAppSecret,
		})
		_node.PlatformAppSecret = value
	}
	if value, ok := pc.mutation.RedirectURL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: platform.FieldRedirectURL,
		})
		_node.RedirectURL = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Platform.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlatformUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (pc *PlatformCreate) OnConflict(opts ...sql.ConflictOption) *PlatformUpsertOne {
	pc.conflict = opts
	return &PlatformUpsertOne{
		create: pc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Platform.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (pc *PlatformCreate) OnConflictColumns(columns ...string) *PlatformUpsertOne {
	pc.conflict = append(pc.conflict, sql.ConflictColumns(columns...))
	return &PlatformUpsertOne{
		create: pc,
	}
}

type (
	// PlatformUpsertOne is the builder for "upsert"-ing
	//  one Platform node.
	PlatformUpsertOne struct {
		create *PlatformCreate
	}

	// PlatformUpsert is the "OnConflict" setter.
	PlatformUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *PlatformUpsert) SetCreatedAt(v uint32) *PlatformUpsert {
	u.Set(platform.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *PlatformUpsert) UpdateCreatedAt() *PlatformUpsert {
	u.SetExcluded(platform.FieldCreatedAt)
	return u
}

// AddCreatedAt adds v to the "created_at" field.
func (u *PlatformUpsert) AddCreatedAt(v uint32) *PlatformUpsert {
	u.Add(platform.FieldCreatedAt, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PlatformUpsert) SetUpdatedAt(v uint32) *PlatformUpsert {
	u.Set(platform.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlatformUpsert) UpdateUpdatedAt() *PlatformUpsert {
	u.SetExcluded(platform.FieldUpdatedAt)
	return u
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *PlatformUpsert) AddUpdatedAt(v uint32) *PlatformUpsert {
	u.Add(platform.FieldUpdatedAt, v)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PlatformUpsert) SetDeletedAt(v uint32) *PlatformUpsert {
	u.Set(platform.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PlatformUpsert) UpdateDeletedAt() *PlatformUpsert {
	u.SetExcluded(platform.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *PlatformUpsert) AddDeletedAt(v uint32) *PlatformUpsert {
	u.Add(platform.FieldDeletedAt, v)
	return u
}

// SetAppID sets the "app_id" field.
func (u *PlatformUpsert) SetAppID(v uuid.UUID) *PlatformUpsert {
	u.Set(platform.FieldAppID, v)
	return u
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *PlatformUpsert) UpdateAppID() *PlatformUpsert {
	u.SetExcluded(platform.FieldAppID)
	return u
}

// SetPlatform sets the "platform" field.
func (u *PlatformUpsert) SetPlatform(v string) *PlatformUpsert {
	u.Set(platform.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *PlatformUpsert) UpdatePlatform() *PlatformUpsert {
	u.SetExcluded(platform.FieldPlatform)
	return u
}

// SetPlatformAuthURL sets the "platform_auth_url" field.
func (u *PlatformUpsert) SetPlatformAuthURL(v string) *PlatformUpsert {
	u.Set(platform.FieldPlatformAuthURL, v)
	return u
}

// UpdatePlatformAuthURL sets the "platform_auth_url" field to the value that was provided on create.
func (u *PlatformUpsert) UpdatePlatformAuthURL() *PlatformUpsert {
	u.SetExcluded(platform.FieldPlatformAuthURL)
	return u
}

// SetLogoURL sets the "logo_url" field.
func (u *PlatformUpsert) SetLogoURL(v string) *PlatformUpsert {
	u.Set(platform.FieldLogoURL, v)
	return u
}

// UpdateLogoURL sets the "logo_url" field to the value that was provided on create.
func (u *PlatformUpsert) UpdateLogoURL() *PlatformUpsert {
	u.SetExcluded(platform.FieldLogoURL)
	return u
}

// SetPlatformAppKey sets the "platform_app_key" field.
func (u *PlatformUpsert) SetPlatformAppKey(v string) *PlatformUpsert {
	u.Set(platform.FieldPlatformAppKey, v)
	return u
}

// UpdatePlatformAppKey sets the "platform_app_key" field to the value that was provided on create.
func (u *PlatformUpsert) UpdatePlatformAppKey() *PlatformUpsert {
	u.SetExcluded(platform.FieldPlatformAppKey)
	return u
}

// SetPlatformAppSecret sets the "platform_app_secret" field.
func (u *PlatformUpsert) SetPlatformAppSecret(v string) *PlatformUpsert {
	u.Set(platform.FieldPlatformAppSecret, v)
	return u
}

// UpdatePlatformAppSecret sets the "platform_app_secret" field to the value that was provided on create.
func (u *PlatformUpsert) UpdatePlatformAppSecret() *PlatformUpsert {
	u.SetExcluded(platform.FieldPlatformAppSecret)
	return u
}

// SetRedirectURL sets the "redirect_url" field.
func (u *PlatformUpsert) SetRedirectURL(v string) *PlatformUpsert {
	u.Set(platform.FieldRedirectURL, v)
	return u
}

// UpdateRedirectURL sets the "redirect_url" field to the value that was provided on create.
func (u *PlatformUpsert) UpdateRedirectURL() *PlatformUpsert {
	u.SetExcluded(platform.FieldRedirectURL)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Platform.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(platform.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *PlatformUpsertOne) UpdateNewValues() *PlatformUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(platform.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.Platform.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *PlatformUpsertOne) Ignore() *PlatformUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlatformUpsertOne) DoNothing() *PlatformUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlatformCreate.OnConflict
// documentation for more info.
func (u *PlatformUpsertOne) Update(set func(*PlatformUpsert)) *PlatformUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlatformUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *PlatformUpsertOne) SetCreatedAt(v uint32) *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *PlatformUpsertOne) AddCreatedAt(v uint32) *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *PlatformUpsertOne) UpdateCreatedAt() *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PlatformUpsertOne) SetUpdatedAt(v uint32) *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *PlatformUpsertOne) AddUpdatedAt(v uint32) *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlatformUpsertOne) UpdateUpdatedAt() *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PlatformUpsertOne) SetDeletedAt(v uint32) *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *PlatformUpsertOne) AddDeletedAt(v uint32) *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PlatformUpsertOne) UpdateDeletedAt() *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetAppID sets the "app_id" field.
func (u *PlatformUpsertOne) SetAppID(v uuid.UUID) *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *PlatformUpsertOne) UpdateAppID() *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateAppID()
	})
}

// SetPlatform sets the "platform" field.
func (u *PlatformUpsertOne) SetPlatform(v string) *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *PlatformUpsertOne) UpdatePlatform() *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdatePlatform()
	})
}

// SetPlatformAuthURL sets the "platform_auth_url" field.
func (u *PlatformUpsertOne) SetPlatformAuthURL(v string) *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.SetPlatformAuthURL(v)
	})
}

// UpdatePlatformAuthURL sets the "platform_auth_url" field to the value that was provided on create.
func (u *PlatformUpsertOne) UpdatePlatformAuthURL() *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdatePlatformAuthURL()
	})
}

// SetLogoURL sets the "logo_url" field.
func (u *PlatformUpsertOne) SetLogoURL(v string) *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.SetLogoURL(v)
	})
}

// UpdateLogoURL sets the "logo_url" field to the value that was provided on create.
func (u *PlatformUpsertOne) UpdateLogoURL() *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateLogoURL()
	})
}

// SetPlatformAppKey sets the "platform_app_key" field.
func (u *PlatformUpsertOne) SetPlatformAppKey(v string) *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.SetPlatformAppKey(v)
	})
}

// UpdatePlatformAppKey sets the "platform_app_key" field to the value that was provided on create.
func (u *PlatformUpsertOne) UpdatePlatformAppKey() *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdatePlatformAppKey()
	})
}

// SetPlatformAppSecret sets the "platform_app_secret" field.
func (u *PlatformUpsertOne) SetPlatformAppSecret(v string) *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.SetPlatformAppSecret(v)
	})
}

// UpdatePlatformAppSecret sets the "platform_app_secret" field to the value that was provided on create.
func (u *PlatformUpsertOne) UpdatePlatformAppSecret() *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdatePlatformAppSecret()
	})
}

// SetRedirectURL sets the "redirect_url" field.
func (u *PlatformUpsertOne) SetRedirectURL(v string) *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.SetRedirectURL(v)
	})
}

// UpdateRedirectURL sets the "redirect_url" field to the value that was provided on create.
func (u *PlatformUpsertOne) UpdateRedirectURL() *PlatformUpsertOne {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateRedirectURL()
	})
}

// Exec executes the query.
func (u *PlatformUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PlatformCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlatformUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PlatformUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PlatformUpsertOne.ID is not supported by MySQL driver. Use PlatformUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PlatformUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PlatformCreateBulk is the builder for creating many Platform entities in bulk.
type PlatformCreateBulk struct {
	config
	builders []*PlatformCreate
	conflict []sql.ConflictOption
}

// Save creates the Platform entities in the database.
func (pcb *PlatformCreateBulk) Save(ctx context.Context) ([]*Platform, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Platform, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlatformMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = pcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PlatformCreateBulk) SaveX(ctx context.Context) []*Platform {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PlatformCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PlatformCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Platform.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlatformUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (pcb *PlatformCreateBulk) OnConflict(opts ...sql.ConflictOption) *PlatformUpsertBulk {
	pcb.conflict = opts
	return &PlatformUpsertBulk{
		create: pcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Platform.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (pcb *PlatformCreateBulk) OnConflictColumns(columns ...string) *PlatformUpsertBulk {
	pcb.conflict = append(pcb.conflict, sql.ConflictColumns(columns...))
	return &PlatformUpsertBulk{
		create: pcb,
	}
}

// PlatformUpsertBulk is the builder for "upsert"-ing
// a bulk of Platform nodes.
type PlatformUpsertBulk struct {
	create *PlatformCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Platform.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(platform.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *PlatformUpsertBulk) UpdateNewValues() *PlatformUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(platform.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Platform.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *PlatformUpsertBulk) Ignore() *PlatformUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlatformUpsertBulk) DoNothing() *PlatformUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlatformCreateBulk.OnConflict
// documentation for more info.
func (u *PlatformUpsertBulk) Update(set func(*PlatformUpsert)) *PlatformUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlatformUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *PlatformUpsertBulk) SetCreatedAt(v uint32) *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *PlatformUpsertBulk) AddCreatedAt(v uint32) *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *PlatformUpsertBulk) UpdateCreatedAt() *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PlatformUpsertBulk) SetUpdatedAt(v uint32) *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *PlatformUpsertBulk) AddUpdatedAt(v uint32) *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlatformUpsertBulk) UpdateUpdatedAt() *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PlatformUpsertBulk) SetDeletedAt(v uint32) *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *PlatformUpsertBulk) AddDeletedAt(v uint32) *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PlatformUpsertBulk) UpdateDeletedAt() *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetAppID sets the "app_id" field.
func (u *PlatformUpsertBulk) SetAppID(v uuid.UUID) *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *PlatformUpsertBulk) UpdateAppID() *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateAppID()
	})
}

// SetPlatform sets the "platform" field.
func (u *PlatformUpsertBulk) SetPlatform(v string) *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *PlatformUpsertBulk) UpdatePlatform() *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdatePlatform()
	})
}

// SetPlatformAuthURL sets the "platform_auth_url" field.
func (u *PlatformUpsertBulk) SetPlatformAuthURL(v string) *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.SetPlatformAuthURL(v)
	})
}

// UpdatePlatformAuthURL sets the "platform_auth_url" field to the value that was provided on create.
func (u *PlatformUpsertBulk) UpdatePlatformAuthURL() *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdatePlatformAuthURL()
	})
}

// SetLogoURL sets the "logo_url" field.
func (u *PlatformUpsertBulk) SetLogoURL(v string) *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.SetLogoURL(v)
	})
}

// UpdateLogoURL sets the "logo_url" field to the value that was provided on create.
func (u *PlatformUpsertBulk) UpdateLogoURL() *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateLogoURL()
	})
}

// SetPlatformAppKey sets the "platform_app_key" field.
func (u *PlatformUpsertBulk) SetPlatformAppKey(v string) *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.SetPlatformAppKey(v)
	})
}

// UpdatePlatformAppKey sets the "platform_app_key" field to the value that was provided on create.
func (u *PlatformUpsertBulk) UpdatePlatformAppKey() *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdatePlatformAppKey()
	})
}

// SetPlatformAppSecret sets the "platform_app_secret" field.
func (u *PlatformUpsertBulk) SetPlatformAppSecret(v string) *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.SetPlatformAppSecret(v)
	})
}

// UpdatePlatformAppSecret sets the "platform_app_secret" field to the value that was provided on create.
func (u *PlatformUpsertBulk) UpdatePlatformAppSecret() *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdatePlatformAppSecret()
	})
}

// SetRedirectURL sets the "redirect_url" field.
func (u *PlatformUpsertBulk) SetRedirectURL(v string) *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.SetRedirectURL(v)
	})
}

// UpdateRedirectURL sets the "redirect_url" field to the value that was provided on create.
func (u *PlatformUpsertBulk) UpdateRedirectURL() *PlatformUpsertBulk {
	return u.Update(func(s *PlatformUpsert) {
		s.UpdateRedirectURL()
	})
}

// Exec executes the query.
func (u *PlatformUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PlatformCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PlatformCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlatformUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
