// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/notification/pkg/db/ent/template"
	"github.com/google/uuid"
)

// TemplateCreate is the builder for creating a Template entity.
type TemplateCreate struct {
	config
	mutation *TemplateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetContent sets the "content" field.
func (tc *TemplateCreate) SetContent(s string) *TemplateCreate {
	tc.mutation.SetContent(s)
	return tc
}

// SetAppID sets the "app_id" field.
func (tc *TemplateCreate) SetAppID(u uuid.UUID) *TemplateCreate {
	tc.mutation.SetAppID(u)
	return tc
}

// SetLangID sets the "lang_id" field.
func (tc *TemplateCreate) SetLangID(u uuid.UUID) *TemplateCreate {
	tc.mutation.SetLangID(u)
	return tc
}

// SetUsedFor sets the "used_for" field.
func (tc *TemplateCreate) SetUsedFor(s string) *TemplateCreate {
	tc.mutation.SetUsedFor(s)
	return tc
}

// SetCreateAt sets the "create_at" field.
func (tc *TemplateCreate) SetCreateAt(u uint32) *TemplateCreate {
	tc.mutation.SetCreateAt(u)
	return tc
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (tc *TemplateCreate) SetNillableCreateAt(u *uint32) *TemplateCreate {
	if u != nil {
		tc.SetCreateAt(*u)
	}
	return tc
}

// SetUpdateAt sets the "update_at" field.
func (tc *TemplateCreate) SetUpdateAt(u uint32) *TemplateCreate {
	tc.mutation.SetUpdateAt(u)
	return tc
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (tc *TemplateCreate) SetNillableUpdateAt(u *uint32) *TemplateCreate {
	if u != nil {
		tc.SetUpdateAt(*u)
	}
	return tc
}

// SetDeleteAt sets the "delete_at" field.
func (tc *TemplateCreate) SetDeleteAt(u uint32) *TemplateCreate {
	tc.mutation.SetDeleteAt(u)
	return tc
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (tc *TemplateCreate) SetNillableDeleteAt(u *uint32) *TemplateCreate {
	if u != nil {
		tc.SetDeleteAt(*u)
	}
	return tc
}

// SetTitle sets the "title" field.
func (tc *TemplateCreate) SetTitle(s string) *TemplateCreate {
	tc.mutation.SetTitle(s)
	return tc
}

// SetID sets the "id" field.
func (tc *TemplateCreate) SetID(u uuid.UUID) *TemplateCreate {
	tc.mutation.SetID(u)
	return tc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tc *TemplateCreate) SetNillableID(u *uuid.UUID) *TemplateCreate {
	if u != nil {
		tc.SetID(*u)
	}
	return tc
}

// Mutation returns the TemplateMutation object of the builder.
func (tc *TemplateCreate) Mutation() *TemplateMutation {
	return tc.mutation
}

// Save creates the Template in the database.
func (tc *TemplateCreate) Save(ctx context.Context) (*Template, error) {
	var (
		err  error
		node *Template
	)
	tc.defaults()
	if len(tc.hooks) == 0 {
		if err = tc.check(); err != nil {
			return nil, err
		}
		node, err = tc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TemplateMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tc.check(); err != nil {
				return nil, err
			}
			tc.mutation = mutation
			if node, err = tc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(tc.hooks) - 1; i >= 0; i-- {
			if tc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TemplateCreate) SaveX(ctx context.Context) *Template {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TemplateCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TemplateCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TemplateCreate) defaults() {
	if _, ok := tc.mutation.CreateAt(); !ok {
		v := template.DefaultCreateAt()
		tc.mutation.SetCreateAt(v)
	}
	if _, ok := tc.mutation.UpdateAt(); !ok {
		v := template.DefaultUpdateAt()
		tc.mutation.SetUpdateAt(v)
	}
	if _, ok := tc.mutation.DeleteAt(); !ok {
		v := template.DefaultDeleteAt()
		tc.mutation.SetDeleteAt(v)
	}
	if _, ok := tc.mutation.ID(); !ok {
		v := template.DefaultID()
		tc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TemplateCreate) check() error {
	if _, ok := tc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Template.content"`)}
	}
	if _, ok := tc.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "Template.app_id"`)}
	}
	if _, ok := tc.mutation.LangID(); !ok {
		return &ValidationError{Name: "lang_id", err: errors.New(`ent: missing required field "Template.lang_id"`)}
	}
	if _, ok := tc.mutation.UsedFor(); !ok {
		return &ValidationError{Name: "used_for", err: errors.New(`ent: missing required field "Template.used_for"`)}
	}
	if _, ok := tc.mutation.CreateAt(); !ok {
		return &ValidationError{Name: "create_at", err: errors.New(`ent: missing required field "Template.create_at"`)}
	}
	if _, ok := tc.mutation.UpdateAt(); !ok {
		return &ValidationError{Name: "update_at", err: errors.New(`ent: missing required field "Template.update_at"`)}
	}
	if _, ok := tc.mutation.DeleteAt(); !ok {
		return &ValidationError{Name: "delete_at", err: errors.New(`ent: missing required field "Template.delete_at"`)}
	}
	if _, ok := tc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Template.title"`)}
	}
	return nil
}

func (tc *TemplateCreate) sqlSave(ctx context.Context) (*Template, error) {
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (tc *TemplateCreate) createSpec() (*Template, *sqlgraph.CreateSpec) {
	var (
		_node = &Template{config: tc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: template.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: template.FieldID,
			},
		}
	)
	_spec.OnConflict = tc.conflict
	if id, ok := tc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tc.mutation.Content(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: template.FieldContent,
		})
		_node.Content = value
	}
	if value, ok := tc.mutation.AppID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: template.FieldAppID,
		})
		_node.AppID = value
	}
	if value, ok := tc.mutation.LangID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: template.FieldLangID,
		})
		_node.LangID = value
	}
	if value, ok := tc.mutation.UsedFor(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: template.FieldUsedFor,
		})
		_node.UsedFor = value
	}
	if value, ok := tc.mutation.CreateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: template.FieldCreateAt,
		})
		_node.CreateAt = value
	}
	if value, ok := tc.mutation.UpdateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: template.FieldUpdateAt,
		})
		_node.UpdateAt = value
	}
	if value, ok := tc.mutation.DeleteAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: template.FieldDeleteAt,
		})
		_node.DeleteAt = value
	}
	if value, ok := tc.mutation.Title(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: template.FieldTitle,
		})
		_node.Title = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Template.Create().
//		SetContent(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TemplateUpsert) {
//			SetContent(v+v).
//		}).
//		Exec(ctx)
//
func (tc *TemplateCreate) OnConflict(opts ...sql.ConflictOption) *TemplateUpsertOne {
	tc.conflict = opts
	return &TemplateUpsertOne{
		create: tc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Template.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (tc *TemplateCreate) OnConflictColumns(columns ...string) *TemplateUpsertOne {
	tc.conflict = append(tc.conflict, sql.ConflictColumns(columns...))
	return &TemplateUpsertOne{
		create: tc,
	}
}

type (
	// TemplateUpsertOne is the builder for "upsert"-ing
	//  one Template node.
	TemplateUpsertOne struct {
		create *TemplateCreate
	}

	// TemplateUpsert is the "OnConflict" setter.
	TemplateUpsert struct {
		*sql.UpdateSet
	}
)

// SetContent sets the "content" field.
func (u *TemplateUpsert) SetContent(v string) *TemplateUpsert {
	u.Set(template.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateContent() *TemplateUpsert {
	u.SetExcluded(template.FieldContent)
	return u
}

// SetAppID sets the "app_id" field.
func (u *TemplateUpsert) SetAppID(v uuid.UUID) *TemplateUpsert {
	u.Set(template.FieldAppID, v)
	return u
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateAppID() *TemplateUpsert {
	u.SetExcluded(template.FieldAppID)
	return u
}

// SetLangID sets the "lang_id" field.
func (u *TemplateUpsert) SetLangID(v uuid.UUID) *TemplateUpsert {
	u.Set(template.FieldLangID, v)
	return u
}

// UpdateLangID sets the "lang_id" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateLangID() *TemplateUpsert {
	u.SetExcluded(template.FieldLangID)
	return u
}

// SetUsedFor sets the "used_for" field.
func (u *TemplateUpsert) SetUsedFor(v string) *TemplateUpsert {
	u.Set(template.FieldUsedFor, v)
	return u
}

// UpdateUsedFor sets the "used_for" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateUsedFor() *TemplateUpsert {
	u.SetExcluded(template.FieldUsedFor)
	return u
}

// SetCreateAt sets the "create_at" field.
func (u *TemplateUpsert) SetCreateAt(v uint32) *TemplateUpsert {
	u.Set(template.FieldCreateAt, v)
	return u
}

// UpdateCreateAt sets the "create_at" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateCreateAt() *TemplateUpsert {
	u.SetExcluded(template.FieldCreateAt)
	return u
}

// AddCreateAt adds v to the "create_at" field.
func (u *TemplateUpsert) AddCreateAt(v uint32) *TemplateUpsert {
	u.Add(template.FieldCreateAt, v)
	return u
}

// SetUpdateAt sets the "update_at" field.
func (u *TemplateUpsert) SetUpdateAt(v uint32) *TemplateUpsert {
	u.Set(template.FieldUpdateAt, v)
	return u
}

// UpdateUpdateAt sets the "update_at" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateUpdateAt() *TemplateUpsert {
	u.SetExcluded(template.FieldUpdateAt)
	return u
}

// AddUpdateAt adds v to the "update_at" field.
func (u *TemplateUpsert) AddUpdateAt(v uint32) *TemplateUpsert {
	u.Add(template.FieldUpdateAt, v)
	return u
}

// SetDeleteAt sets the "delete_at" field.
func (u *TemplateUpsert) SetDeleteAt(v uint32) *TemplateUpsert {
	u.Set(template.FieldDeleteAt, v)
	return u
}

// UpdateDeleteAt sets the "delete_at" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateDeleteAt() *TemplateUpsert {
	u.SetExcluded(template.FieldDeleteAt)
	return u
}

// AddDeleteAt adds v to the "delete_at" field.
func (u *TemplateUpsert) AddDeleteAt(v uint32) *TemplateUpsert {
	u.Add(template.FieldDeleteAt, v)
	return u
}

// SetTitle sets the "title" field.
func (u *TemplateUpsert) SetTitle(v string) *TemplateUpsert {
	u.Set(template.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *TemplateUpsert) UpdateTitle() *TemplateUpsert {
	u.SetExcluded(template.FieldTitle)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Template.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(template.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *TemplateUpsertOne) UpdateNewValues() *TemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(template.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.Template.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *TemplateUpsertOne) Ignore() *TemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TemplateUpsertOne) DoNothing() *TemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TemplateCreate.OnConflict
// documentation for more info.
func (u *TemplateUpsertOne) Update(set func(*TemplateUpsert)) *TemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetContent sets the "content" field.
func (u *TemplateUpsertOne) SetContent(v string) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateContent() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateContent()
	})
}

// SetAppID sets the "app_id" field.
func (u *TemplateUpsertOne) SetAppID(v uuid.UUID) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateAppID() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateAppID()
	})
}

// SetLangID sets the "lang_id" field.
func (u *TemplateUpsertOne) SetLangID(v uuid.UUID) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetLangID(v)
	})
}

// UpdateLangID sets the "lang_id" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateLangID() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateLangID()
	})
}

// SetUsedFor sets the "used_for" field.
func (u *TemplateUpsertOne) SetUsedFor(v string) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetUsedFor(v)
	})
}

// UpdateUsedFor sets the "used_for" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateUsedFor() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateUsedFor()
	})
}

// SetCreateAt sets the "create_at" field.
func (u *TemplateUpsertOne) SetCreateAt(v uint32) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetCreateAt(v)
	})
}

// AddCreateAt adds v to the "create_at" field.
func (u *TemplateUpsertOne) AddCreateAt(v uint32) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.AddCreateAt(v)
	})
}

// UpdateCreateAt sets the "create_at" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateCreateAt() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateCreateAt()
	})
}

// SetUpdateAt sets the "update_at" field.
func (u *TemplateUpsertOne) SetUpdateAt(v uint32) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetUpdateAt(v)
	})
}

// AddUpdateAt adds v to the "update_at" field.
func (u *TemplateUpsertOne) AddUpdateAt(v uint32) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.AddUpdateAt(v)
	})
}

// UpdateUpdateAt sets the "update_at" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateUpdateAt() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateUpdateAt()
	})
}

// SetDeleteAt sets the "delete_at" field.
func (u *TemplateUpsertOne) SetDeleteAt(v uint32) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetDeleteAt(v)
	})
}

// AddDeleteAt adds v to the "delete_at" field.
func (u *TemplateUpsertOne) AddDeleteAt(v uint32) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.AddDeleteAt(v)
	})
}

// UpdateDeleteAt sets the "delete_at" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateDeleteAt() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateDeleteAt()
	})
}

// SetTitle sets the "title" field.
func (u *TemplateUpsertOne) SetTitle(v string) *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *TemplateUpsertOne) UpdateTitle() *TemplateUpsertOne {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateTitle()
	})
}

// Exec executes the query.
func (u *TemplateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TemplateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TemplateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TemplateUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TemplateUpsertOne.ID is not supported by MySQL driver. Use TemplateUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TemplateUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TemplateCreateBulk is the builder for creating many Template entities in bulk.
type TemplateCreateBulk struct {
	config
	builders []*TemplateCreate
	conflict []sql.ConflictOption
}

// Save creates the Template entities in the database.
func (tcb *TemplateCreateBulk) Save(ctx context.Context) ([]*Template, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Template, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = tcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TemplateCreateBulk) SaveX(ctx context.Context) []*Template {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TemplateCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Template.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TemplateUpsert) {
//			SetContent(v+v).
//		}).
//		Exec(ctx)
//
func (tcb *TemplateCreateBulk) OnConflict(opts ...sql.ConflictOption) *TemplateUpsertBulk {
	tcb.conflict = opts
	return &TemplateUpsertBulk{
		create: tcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Template.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (tcb *TemplateCreateBulk) OnConflictColumns(columns ...string) *TemplateUpsertBulk {
	tcb.conflict = append(tcb.conflict, sql.ConflictColumns(columns...))
	return &TemplateUpsertBulk{
		create: tcb,
	}
}

// TemplateUpsertBulk is the builder for "upsert"-ing
// a bulk of Template nodes.
type TemplateUpsertBulk struct {
	create *TemplateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Template.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(template.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *TemplateUpsertBulk) UpdateNewValues() *TemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(template.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Template.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *TemplateUpsertBulk) Ignore() *TemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TemplateUpsertBulk) DoNothing() *TemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TemplateCreateBulk.OnConflict
// documentation for more info.
func (u *TemplateUpsertBulk) Update(set func(*TemplateUpsert)) *TemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetContent sets the "content" field.
func (u *TemplateUpsertBulk) SetContent(v string) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateContent() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateContent()
	})
}

// SetAppID sets the "app_id" field.
func (u *TemplateUpsertBulk) SetAppID(v uuid.UUID) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateAppID() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateAppID()
	})
}

// SetLangID sets the "lang_id" field.
func (u *TemplateUpsertBulk) SetLangID(v uuid.UUID) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetLangID(v)
	})
}

// UpdateLangID sets the "lang_id" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateLangID() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateLangID()
	})
}

// SetUsedFor sets the "used_for" field.
func (u *TemplateUpsertBulk) SetUsedFor(v string) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetUsedFor(v)
	})
}

// UpdateUsedFor sets the "used_for" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateUsedFor() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateUsedFor()
	})
}

// SetCreateAt sets the "create_at" field.
func (u *TemplateUpsertBulk) SetCreateAt(v uint32) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetCreateAt(v)
	})
}

// AddCreateAt adds v to the "create_at" field.
func (u *TemplateUpsertBulk) AddCreateAt(v uint32) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.AddCreateAt(v)
	})
}

// UpdateCreateAt sets the "create_at" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateCreateAt() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateCreateAt()
	})
}

// SetUpdateAt sets the "update_at" field.
func (u *TemplateUpsertBulk) SetUpdateAt(v uint32) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetUpdateAt(v)
	})
}

// AddUpdateAt adds v to the "update_at" field.
func (u *TemplateUpsertBulk) AddUpdateAt(v uint32) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.AddUpdateAt(v)
	})
}

// UpdateUpdateAt sets the "update_at" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateUpdateAt() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateUpdateAt()
	})
}

// SetDeleteAt sets the "delete_at" field.
func (u *TemplateUpsertBulk) SetDeleteAt(v uint32) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetDeleteAt(v)
	})
}

// AddDeleteAt adds v to the "delete_at" field.
func (u *TemplateUpsertBulk) AddDeleteAt(v uint32) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.AddDeleteAt(v)
	})
}

// UpdateDeleteAt sets the "delete_at" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateDeleteAt() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateDeleteAt()
	})
}

// SetTitle sets the "title" field.
func (u *TemplateUpsertBulk) SetTitle(v string) *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *TemplateUpsertBulk) UpdateTitle() *TemplateUpsertBulk {
	return u.Update(func(s *TemplateUpsert) {
		s.UpdateTitle()
	})
}

// Exec executes the query.
func (u *TemplateUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TemplateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TemplateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TemplateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
