// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/third-login-gateway/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/third-login-gateway/pkg/db/ent/thirdauth"
	"github.com/google/uuid"
)

// ThirdAuthQuery is the builder for querying ThirdAuth entities.
type ThirdAuthQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ThirdAuth
	modifiers  []func(s *sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ThirdAuthQuery builder.
func (taq *ThirdAuthQuery) Where(ps ...predicate.ThirdAuth) *ThirdAuthQuery {
	taq.predicates = append(taq.predicates, ps...)
	return taq
}

// Limit adds a limit step to the query.
func (taq *ThirdAuthQuery) Limit(limit int) *ThirdAuthQuery {
	taq.limit = &limit
	return taq
}

// Offset adds an offset step to the query.
func (taq *ThirdAuthQuery) Offset(offset int) *ThirdAuthQuery {
	taq.offset = &offset
	return taq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (taq *ThirdAuthQuery) Unique(unique bool) *ThirdAuthQuery {
	taq.unique = &unique
	return taq
}

// Order adds an order step to the query.
func (taq *ThirdAuthQuery) Order(o ...OrderFunc) *ThirdAuthQuery {
	taq.order = append(taq.order, o...)
	return taq
}

// First returns the first ThirdAuth entity from the query.
// Returns a *NotFoundError when no ThirdAuth was found.
func (taq *ThirdAuthQuery) First(ctx context.Context) (*ThirdAuth, error) {
	nodes, err := taq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{thirdauth.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (taq *ThirdAuthQuery) FirstX(ctx context.Context) *ThirdAuth {
	node, err := taq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ThirdAuth ID from the query.
// Returns a *NotFoundError when no ThirdAuth ID was found.
func (taq *ThirdAuthQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = taq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{thirdauth.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (taq *ThirdAuthQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := taq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ThirdAuth entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ThirdAuth entity is found.
// Returns a *NotFoundError when no ThirdAuth entities are found.
func (taq *ThirdAuthQuery) Only(ctx context.Context) (*ThirdAuth, error) {
	nodes, err := taq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{thirdauth.Label}
	default:
		return nil, &NotSingularError{thirdauth.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (taq *ThirdAuthQuery) OnlyX(ctx context.Context) *ThirdAuth {
	node, err := taq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ThirdAuth ID in the query.
// Returns a *NotSingularError when more than one ThirdAuth ID is found.
// Returns a *NotFoundError when no entities are found.
func (taq *ThirdAuthQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = taq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{thirdauth.Label}
	default:
		err = &NotSingularError{thirdauth.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (taq *ThirdAuthQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := taq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ThirdAuths.
func (taq *ThirdAuthQuery) All(ctx context.Context) ([]*ThirdAuth, error) {
	if err := taq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return taq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (taq *ThirdAuthQuery) AllX(ctx context.Context) []*ThirdAuth {
	nodes, err := taq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ThirdAuth IDs.
func (taq *ThirdAuthQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := taq.Select(thirdauth.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (taq *ThirdAuthQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := taq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (taq *ThirdAuthQuery) Count(ctx context.Context) (int, error) {
	if err := taq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return taq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (taq *ThirdAuthQuery) CountX(ctx context.Context) int {
	count, err := taq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (taq *ThirdAuthQuery) Exist(ctx context.Context) (bool, error) {
	if err := taq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return taq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (taq *ThirdAuthQuery) ExistX(ctx context.Context) bool {
	exist, err := taq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ThirdAuthQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (taq *ThirdAuthQuery) Clone() *ThirdAuthQuery {
	if taq == nil {
		return nil
	}
	return &ThirdAuthQuery{
		config:     taq.config,
		limit:      taq.limit,
		offset:     taq.offset,
		order:      append([]OrderFunc{}, taq.order...),
		predicates: append([]predicate.ThirdAuth{}, taq.predicates...),
		// clone intermediate query.
		sql:    taq.sql.Clone(),
		path:   taq.path,
		unique: taq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ThirdAuth.Query().
//		GroupBy(thirdauth.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (taq *ThirdAuthQuery) GroupBy(field string, fields ...string) *ThirdAuthGroupBy {
	group := &ThirdAuthGroupBy{config: taq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := taq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return taq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.ThirdAuth.Query().
//		Select(thirdauth.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (taq *ThirdAuthQuery) Select(fields ...string) *ThirdAuthSelect {
	taq.fields = append(taq.fields, fields...)
	return &ThirdAuthSelect{ThirdAuthQuery: taq}
}

func (taq *ThirdAuthQuery) prepareQuery(ctx context.Context) error {
	for _, f := range taq.fields {
		if !thirdauth.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if taq.path != nil {
		prev, err := taq.path(ctx)
		if err != nil {
			return err
		}
		taq.sql = prev
	}
	return nil
}

func (taq *ThirdAuthQuery) sqlAll(ctx context.Context) ([]*ThirdAuth, error) {
	var (
		nodes = []*ThirdAuth{}
		_spec = taq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ThirdAuth{config: taq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if len(taq.modifiers) > 0 {
		_spec.Modifiers = taq.modifiers
	}
	if err := sqlgraph.QueryNodes(ctx, taq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (taq *ThirdAuthQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := taq.querySpec()
	if len(taq.modifiers) > 0 {
		_spec.Modifiers = taq.modifiers
	}
	_spec.Node.Columns = taq.fields
	if len(taq.fields) > 0 {
		_spec.Unique = taq.unique != nil && *taq.unique
	}
	return sqlgraph.CountNodes(ctx, taq.driver, _spec)
}

func (taq *ThirdAuthQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := taq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (taq *ThirdAuthQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   thirdauth.Table,
			Columns: thirdauth.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: thirdauth.FieldID,
			},
		},
		From:   taq.sql,
		Unique: true,
	}
	if unique := taq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := taq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, thirdauth.FieldID)
		for i := range fields {
			if fields[i] != thirdauth.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := taq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := taq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := taq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := taq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (taq *ThirdAuthQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(taq.driver.Dialect())
	t1 := builder.Table(thirdauth.Table)
	columns := taq.fields
	if len(columns) == 0 {
		columns = thirdauth.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if taq.sql != nil {
		selector = taq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if taq.unique != nil && *taq.unique {
		selector.Distinct()
	}
	for _, m := range taq.modifiers {
		m(selector)
	}
	for _, p := range taq.predicates {
		p(selector)
	}
	for _, p := range taq.order {
		p(selector)
	}
	if offset := taq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := taq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (taq *ThirdAuthQuery) ForUpdate(opts ...sql.LockOption) *ThirdAuthQuery {
	if taq.driver.Dialect() == dialect.Postgres {
		taq.Unique(false)
	}
	taq.modifiers = append(taq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return taq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (taq *ThirdAuthQuery) ForShare(opts ...sql.LockOption) *ThirdAuthQuery {
	if taq.driver.Dialect() == dialect.Postgres {
		taq.Unique(false)
	}
	taq.modifiers = append(taq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return taq
}

// ThirdAuthGroupBy is the group-by builder for ThirdAuth entities.
type ThirdAuthGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tagb *ThirdAuthGroupBy) Aggregate(fns ...AggregateFunc) *ThirdAuthGroupBy {
	tagb.fns = append(tagb.fns, fns...)
	return tagb
}

// Scan applies the group-by query and scans the result into the given value.
func (tagb *ThirdAuthGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tagb.path(ctx)
	if err != nil {
		return err
	}
	tagb.sql = query
	return tagb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tagb *ThirdAuthGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := tagb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (tagb *ThirdAuthGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(tagb.fields) > 1 {
		return nil, errors.New("ent: ThirdAuthGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := tagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tagb *ThirdAuthGroupBy) StringsX(ctx context.Context) []string {
	v, err := tagb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tagb *ThirdAuthGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tagb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{thirdauth.Label}
	default:
		err = fmt.Errorf("ent: ThirdAuthGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tagb *ThirdAuthGroupBy) StringX(ctx context.Context) string {
	v, err := tagb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (tagb *ThirdAuthGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(tagb.fields) > 1 {
		return nil, errors.New("ent: ThirdAuthGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := tagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tagb *ThirdAuthGroupBy) IntsX(ctx context.Context) []int {
	v, err := tagb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tagb *ThirdAuthGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tagb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{thirdauth.Label}
	default:
		err = fmt.Errorf("ent: ThirdAuthGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tagb *ThirdAuthGroupBy) IntX(ctx context.Context) int {
	v, err := tagb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (tagb *ThirdAuthGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(tagb.fields) > 1 {
		return nil, errors.New("ent: ThirdAuthGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := tagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tagb *ThirdAuthGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := tagb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tagb *ThirdAuthGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tagb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{thirdauth.Label}
	default:
		err = fmt.Errorf("ent: ThirdAuthGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tagb *ThirdAuthGroupBy) Float64X(ctx context.Context) float64 {
	v, err := tagb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (tagb *ThirdAuthGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(tagb.fields) > 1 {
		return nil, errors.New("ent: ThirdAuthGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := tagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tagb *ThirdAuthGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := tagb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tagb *ThirdAuthGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tagb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{thirdauth.Label}
	default:
		err = fmt.Errorf("ent: ThirdAuthGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tagb *ThirdAuthGroupBy) BoolX(ctx context.Context) bool {
	v, err := tagb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tagb *ThirdAuthGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tagb.fields {
		if !thirdauth.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tagb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tagb *ThirdAuthGroupBy) sqlQuery() *sql.Selector {
	selector := tagb.sql.Select()
	aggregation := make([]string, 0, len(tagb.fns))
	for _, fn := range tagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tagb.fields)+len(tagb.fns))
		for _, f := range tagb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tagb.fields...)...)
}

// ThirdAuthSelect is the builder for selecting fields of ThirdAuth entities.
type ThirdAuthSelect struct {
	*ThirdAuthQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tas *ThirdAuthSelect) Scan(ctx context.Context, v interface{}) error {
	if err := tas.prepareQuery(ctx); err != nil {
		return err
	}
	tas.sql = tas.ThirdAuthQuery.sqlQuery(ctx)
	return tas.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tas *ThirdAuthSelect) ScanX(ctx context.Context, v interface{}) {
	if err := tas.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (tas *ThirdAuthSelect) Strings(ctx context.Context) ([]string, error) {
	if len(tas.fields) > 1 {
		return nil, errors.New("ent: ThirdAuthSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := tas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tas *ThirdAuthSelect) StringsX(ctx context.Context) []string {
	v, err := tas.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (tas *ThirdAuthSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tas.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{thirdauth.Label}
	default:
		err = fmt.Errorf("ent: ThirdAuthSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tas *ThirdAuthSelect) StringX(ctx context.Context) string {
	v, err := tas.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (tas *ThirdAuthSelect) Ints(ctx context.Context) ([]int, error) {
	if len(tas.fields) > 1 {
		return nil, errors.New("ent: ThirdAuthSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := tas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tas *ThirdAuthSelect) IntsX(ctx context.Context) []int {
	v, err := tas.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (tas *ThirdAuthSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tas.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{thirdauth.Label}
	default:
		err = fmt.Errorf("ent: ThirdAuthSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tas *ThirdAuthSelect) IntX(ctx context.Context) int {
	v, err := tas.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (tas *ThirdAuthSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(tas.fields) > 1 {
		return nil, errors.New("ent: ThirdAuthSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := tas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tas *ThirdAuthSelect) Float64sX(ctx context.Context) []float64 {
	v, err := tas.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (tas *ThirdAuthSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tas.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{thirdauth.Label}
	default:
		err = fmt.Errorf("ent: ThirdAuthSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tas *ThirdAuthSelect) Float64X(ctx context.Context) float64 {
	v, err := tas.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (tas *ThirdAuthSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(tas.fields) > 1 {
		return nil, errors.New("ent: ThirdAuthSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := tas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tas *ThirdAuthSelect) BoolsX(ctx context.Context) []bool {
	v, err := tas.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (tas *ThirdAuthSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tas.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{thirdauth.Label}
	default:
		err = fmt.Errorf("ent: ThirdAuthSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tas *ThirdAuthSelect) BoolX(ctx context.Context) bool {
	v, err := tas.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tas *ThirdAuthSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tas.sql.Query()
	if err := tas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
