apiVersion: apps/v1
kind: Deployment
metadata:
  name: third-login-gateway
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: third-login-gateway
  template:
    metadata:
      labels:
        app: third-login-gateway
    spec:
      containers:
      - name: third-login-gateway
        image: uhub.service.ucloud.cn/entropypool/third-login-gateway:latest
        imagePullPolicy: Always
        env:
        - name: ENV_ENVIRONMENT_TARGET
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.target
        - name: ENV_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_host
        - name: ENV_CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_port
        - name: ENV_CLUSTER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

---
apiVersion: v1
kind: Service
metadata:
  name: third-login-gateway
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 50280
    targetPort: 50280
  - name: grpc
    port: 50281
    targetPort: 50281
  - name: prometheus
    port: 50283
    targetPort: 50283
  selector:
    app: third-login-gateway
