// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Announcement is the predicate function for announcement builders.
type Announcement func(*sql.Selector)

// MailBox is the predicate function for mailbox builders.
type MailBox func(*sql.Selector)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)

// ReadUser is the predicate function for readuser builders.
type ReadUser func(*sql.Selector)

// Template is the predicate function for template builders.
type Template func(*sql.Selector)
