// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Auth is the predicate function for auth builders.
type Auth func(*sql.Selector)

// ThirdParty is the predicate function for thirdparty builders.
type ThirdParty func(*sql.Selector)
